package com.model;

import java.util.Date;

public class CourseTimeDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coursetime.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coursetime.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coursetime.time
     *
     * @mbg.generated
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coursetime.startime
     *
     * @mbg.generated
     */
    private Date startime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coursetime.course_num
     *
     * @mbg.generated
     */
    private Integer courseNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coursetime.deal_id
     *
     * @mbg.generated
     */
    private Integer dealId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coursetime.id
     *
     * @return the value of coursetime.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coursetime.id
     *
     * @param id the value for coursetime.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coursetime.content
     *
     * @return the value of coursetime.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coursetime.content
     *
     * @param content the value for coursetime.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coursetime.time
     *
     * @return the value of coursetime.time
     *
     * @mbg.generated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coursetime.time
     *
     * @param time the value for coursetime.time
     *
     * @mbg.generated
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coursetime.startime
     *
     * @return the value of coursetime.startime
     *
     * @mbg.generated
     */
    public Date getStartime() {
        return startime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coursetime.startime
     *
     * @param startime the value for coursetime.startime
     *
     * @mbg.generated
     */
    public void setStartime(Date startime) {
        this.startime = startime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coursetime.course_num
     *
     * @return the value of coursetime.course_num
     *
     * @mbg.generated
     */
    public Integer getCourseNum() {
        return courseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coursetime.course_num
     *
     * @param courseNum the value for coursetime.course_num
     *
     * @mbg.generated
     */
    public void setCourseNum(Integer courseNum) {
        this.courseNum = courseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coursetime.deal_id
     *
     * @return the value of coursetime.deal_id
     *
     * @mbg.generated
     */
    public Integer getDealId() {
        return dealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coursetime.deal_id
     *
     * @param dealId the value for coursetime.deal_id
     *
     * @mbg.generated
     */
    public void setDealId(Integer dealId) {
        this.dealId = dealId;
    }
}