package com.model;

public class DealDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.promoter
     *
     * @mbg.generated
     */
    private String promoter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.assist_id
     *
     * @mbg.generated
     */
    private String assistId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.recruit_id
     *
     * @mbg.generated
     */
    private Integer recruitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.star_num
     *
     * @mbg.generated
     */
    private Integer starNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.monry_per_hour
     *
     * @mbg.generated
     */
    private Double monryPerHour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.id
     *
     * @return the value of deal.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.id
     *
     * @param id the value for deal.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.promoter
     *
     * @return the value of deal.promoter
     *
     * @mbg.generated
     */
    public String getPromoter() {
        return promoter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.promoter
     *
     * @param promoter the value for deal.promoter
     *
     * @mbg.generated
     */
    public void setPromoter(String promoter) {
        this.promoter = promoter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.assist_id
     *
     * @return the value of deal.assist_id
     *
     * @mbg.generated
     */
    public String getAssistId() {
        return assistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.assist_id
     *
     * @param assistId the value for deal.assist_id
     *
     * @mbg.generated
     */
    public void setAssistId(String assistId) {
        this.assistId = assistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.recruit_id
     *
     * @return the value of deal.recruit_id
     *
     * @mbg.generated
     */
    public Integer getRecruitId() {
        return recruitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.recruit_id
     *
     * @param recruitId the value for deal.recruit_id
     *
     * @mbg.generated
     */
    public void setRecruitId(Integer recruitId) {
        this.recruitId = recruitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.star_num
     *
     * @return the value of deal.star_num
     *
     * @mbg.generated
     */
    public Integer getStarNum() {
        return starNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.star_num
     *
     * @param starNum the value for deal.star_num
     *
     * @mbg.generated
     */
    public void setStarNum(Integer starNum) {
        this.starNum = starNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.monry_per_hour
     *
     * @return the value of deal.monry_per_hour
     *
     * @mbg.generated
     */
    public Double getMonryPerHour() {
        return monryPerHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.monry_per_hour
     *
     * @param monryPerHour the value for deal.monry_per_hour
     *
     * @mbg.generated
     */
    public void setMonryPerHour(Double monryPerHour) {
        this.monryPerHour = monryPerHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.comment
     *
     * @return the value of deal.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.comment
     *
     * @param comment the value for deal.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment;
    }
}