package com.model;

public class PermissionDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.perm
     *
     * @mbg.generated
     */
    private String perm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.id
     *
     * @return the value of permission.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.id
     *
     * @param id the value for permission.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.perm
     *
     * @return the value of permission.perm
     *
     * @mbg.generated
     */
    public String getPerm() {
        return perm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.perm
     *
     * @param perm the value for permission.perm
     *
     * @mbg.generated
     */
    public void setPerm(String perm) {
        this.perm = perm;
    }
}