package com.model;

public class RolePermDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roleperm.rid
     *
     * @mbg.generated
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roleperm.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roleperm.rid
     *
     * @return the value of roleperm.rid
     *
     * @mbg.generated
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roleperm.rid
     *
     * @param rid the value for roleperm.rid
     *
     * @mbg.generated
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roleperm.pid
     *
     * @return the value of roleperm.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roleperm.pid
     *
     * @param pid the value for roleperm.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}