package com.model;

public class StudentMsgDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentmsg.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentmsg.chinese
     *
     * @mbg.generated
     */
    private Double chinese;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentmsg.math
     *
     * @mbg.generated
     */
    private Double math;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentmsg.english
     *
     * @mbg.generated
     */
    private Double english;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentmsg.arts_or_science
     *
     * @mbg.generated
     */
    private Boolean artsOrScience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentmsg.major
     *
     * @mbg.generated
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentmsg.university
     *
     * @mbg.generated
     */
    private String university;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentmsg.comprehensive_liberal_or_science
     *
     * @mbg.generated
     */
    private Double comprehensiveLiberalOrScience;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentmsg.id
     *
     * @return the value of studentmsg.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentmsg.id
     *
     * @param id the value for studentmsg.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentmsg.chinese
     *
     * @return the value of studentmsg.chinese
     *
     * @mbg.generated
     */
    public Double getChinese() {
        return chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentmsg.chinese
     *
     * @param chinese the value for studentmsg.chinese
     *
     * @mbg.generated
     */
    public void setChinese(Double chinese) {
        this.chinese = chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentmsg.math
     *
     * @return the value of studentmsg.math
     *
     * @mbg.generated
     */
    public Double getMath() {
        return math;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentmsg.math
     *
     * @param math the value for studentmsg.math
     *
     * @mbg.generated
     */
    public void setMath(Double math) {
        this.math = math;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentmsg.english
     *
     * @return the value of studentmsg.english
     *
     * @mbg.generated
     */
    public Double getEnglish() {
        return english;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentmsg.english
     *
     * @param english the value for studentmsg.english
     *
     * @mbg.generated
     */
    public void setEnglish(Double english) {
        this.english = english;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentmsg.arts_or_science
     *
     * @return the value of studentmsg.arts_or_science
     *
     * @mbg.generated
     */
    public Boolean getArtsOrScience() {
        return artsOrScience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentmsg.arts_or_science
     *
     * @param artsOrScience the value for studentmsg.arts_or_science
     *
     * @mbg.generated
     */
    public void setArtsOrScience(Boolean artsOrScience) {
        this.artsOrScience = artsOrScience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentmsg.major
     *
     * @return the value of studentmsg.major
     *
     * @mbg.generated
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentmsg.major
     *
     * @param major the value for studentmsg.major
     *
     * @mbg.generated
     */
    public void setMajor(String major) {
        this.major = major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentmsg.university
     *
     * @return the value of studentmsg.university
     *
     * @mbg.generated
     */
    public String getUniversity() {
        return university;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentmsg.university
     *
     * @param university the value for studentmsg.university
     *
     * @mbg.generated
     */
    public void setUniversity(String university) {
        this.university = university;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentmsg.comprehensive_liberal_or_science
     *
     * @return the value of studentmsg.comprehensive_liberal_or_science
     *
     * @mbg.generated
     */
    public Double getComprehensiveLiberalOrScience() {
        return comprehensiveLiberalOrScience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentmsg.comprehensive_liberal_or_science
     *
     * @param comprehensiveLiberalOrScience the value for studentmsg.comprehensive_liberal_or_science
     *
     * @mbg.generated
     */
    public void setComprehensiveLiberalOrScience(Double comprehensiveLiberalOrScience) {
        this.comprehensiveLiberalOrScience = comprehensiveLiberalOrScience;
    }
}