package com.model;

public class UserMsgDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usermsg.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usermsg.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usermsg.aid
     *
     * @mbg.generated
     */
    private String aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usermsg.payId
     *
     * @mbg.generated
     */
    private String payid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usermsg.role
     *
     * @mbg.generated
     */
    private Integer role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usermsg.id
     *
     * @return the value of usermsg.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usermsg.id
     *
     * @param id the value for usermsg.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usermsg.uid
     *
     * @return the value of usermsg.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usermsg.uid
     *
     * @param uid the value for usermsg.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usermsg.aid
     *
     * @return the value of usermsg.aid
     *
     * @mbg.generated
     */
    public String getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usermsg.aid
     *
     * @param aid the value for usermsg.aid
     *
     * @mbg.generated
     */
    public void setAid(String aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usermsg.payId
     *
     * @return the value of usermsg.payId
     *
     * @mbg.generated
     */
    public String getPayid() {
        return payid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usermsg.payId
     *
     * @param payid the value for usermsg.payId
     *
     * @mbg.generated
     */
    public void setPayid(String payid) {
        this.payid = payid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usermsg.role
     *
     * @return the value of usermsg.role
     *
     * @mbg.generated
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usermsg.role
     *
     * @param role the value for usermsg.role
     *
     * @mbg.generated
     */
    public void setRole(Integer role) {
        this.role = role;
    }
}