package com.mapper;

import com.model.AuthDO;
import com.model.AuthDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated
     */
    long countByExample(AuthDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated
     */
    int deleteByExample(AuthDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated
     */
    int insert(AuthDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated
     */
    int insertSelective(AuthDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated
     */
    List<AuthDO> selectByExample(AuthDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AuthDO record, @Param("example") AuthDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AuthDO record, @Param("example") AuthDOExample example);
}