package com.mapper;

import com.model.DealDO;
import com.model.DealDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DealDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated
     */
    long countByExample(DealDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated
     */
    int deleteByExample(DealDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated
     */
    int insert(DealDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated
     */
    int insertSelective(DealDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated
     */
    List<DealDO> selectByExampleWithBLOBs(DealDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated
     */
    List<DealDO> selectByExample(DealDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DealDO record, @Param("example") DealDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") DealDO record, @Param("example") DealDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DealDO record, @Param("example") DealDOExample example);
}