package com.mapper;

import com.model.RolePermDO;
import com.model.RolePermDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolePermDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleperm
     *
     * @mbg.generated
     */
    long countByExample(RolePermDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleperm
     *
     * @mbg.generated
     */
    int deleteByExample(RolePermDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleperm
     *
     * @mbg.generated
     */
    int insert(RolePermDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleperm
     *
     * @mbg.generated
     */
    int insertSelective(RolePermDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleperm
     *
     * @mbg.generated
     */
    List<RolePermDO> selectByExample(RolePermDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleperm
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RolePermDO record, @Param("example") RolePermDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleperm
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RolePermDO record, @Param("example") RolePermDOExample example);
}