package com.mapper;

import com.model.StudentMsgDO;
import com.model.StudentMsgDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentMsgDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentmsg
     *
     * @mbg.generated
     */
    long countByExample(StudentMsgDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentmsg
     *
     * @mbg.generated
     */
    int deleteByExample(StudentMsgDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentmsg
     *
     * @mbg.generated
     */
    int insert(StudentMsgDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentmsg
     *
     * @mbg.generated
     */
    int insertSelective(StudentMsgDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentmsg
     *
     * @mbg.generated
     */
    List<StudentMsgDO> selectByExample(StudentMsgDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentmsg
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StudentMsgDO record, @Param("example") StudentMsgDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentmsg
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StudentMsgDO record, @Param("example") StudentMsgDOExample example);
}