package com.mapper;

import com.model.TimeDO;
import com.model.TimeDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TimeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time
     *
     * @mbg.generated
     */
    long countByExample(TimeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time
     *
     * @mbg.generated
     */
    int deleteByExample(TimeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time
     *
     * @mbg.generated
     */
    int insert(TimeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time
     *
     * @mbg.generated
     */
    int insertSelective(TimeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time
     *
     * @mbg.generated
     */
    List<TimeDO> selectByExample(TimeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TimeDO record, @Param("example") TimeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TimeDO record, @Param("example") TimeDOExample example);
}