package com.mapper;

import com.model.UserMsgDO;
import com.model.UserMsgDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMsgDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usermsg
     *
     * @mbg.generated
     */
    long countByExample(UserMsgDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usermsg
     *
     * @mbg.generated
     */
    int deleteByExample(UserMsgDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usermsg
     *
     * @mbg.generated
     */
    int insert(UserMsgDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usermsg
     *
     * @mbg.generated
     */
    int insertSelective(UserMsgDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usermsg
     *
     * @mbg.generated
     */
    List<UserMsgDO> selectByExample(UserMsgDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usermsg
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserMsgDO record, @Param("example") UserMsgDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usermsg
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserMsgDO record, @Param("example") UserMsgDOExample example);
}